containerctl: support container workflow

diff --git a/bin/container-start b/bin/container-start
--- a/bin/container-start
+++ b/bin/container-start
@@ -1,10 +1,17 @@
 #!/bin/bash
+set -eu
+
+if [[ -n "$DEBUG" ]]; then
+    set -x
+fi
+
+(( "$#" >= 1 )) && [[ -n "$1" ]] || { echo "Error: usage: container-start container"; exit 1; }
 
 start() {
-    [[ -n "$1" ]] && cd $(readlink -f $(dirname $0)/..)/${1} || exit 1
+    cd $(readlink -f $(dirname $0)/..)/${1} || exit 1
 
-    local name=$(make name)
-    create_as_needed ${name} && make run && podman start ${name}
+    local name=$(make --no-print-directory name)
+    [ -n "$name" ] && create_as_needed "${name}" && make run && podman start "${name}"
 }
 
 is_image() {
@@ -18,9 +25,10 @@ is_container() {
 }
 
 create_as_needed() {
-    if ! is_container "$1"; then
-        if ! is_image "awerlang/$1"; then
-            notify-send "$1" "Image for $1 must be built before use"
+    local name=$1
+    if ! is_container "$name"; then
+        if ! is_image "awerlang/$name"; then
+            notify-send "$name" "Image for $name must be built before use"
         fi
         echo 'Creating container' | grep --color=always .
         make create >/dev/null
